apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: blueprint
spec:
  selector:
    app: blueprint
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
